import { readFileSync, existsSync, globSync } from 'node:fs';

/**
 * PWA SAFETY.
 *
 * Two rules, and the first one is the serious one.
 *
 * ═══ 1. A SERVICE WORKER MUST NEVER CACHE AN AUTHENTICATED RESPONSE ═══
 *
 * A service worker cache is per-DEVICE, not per-user. Cache `/api/bookings` and
 * the next person to sign in on that laptop — a partner, a colleague, the next
 * shift on the club's front desk — is served the PREVIOUS user's data, from
 * disk, without a single request reaching us.
 *
 * There is no session check to fail. There is no log line. The data simply
 * appears under the wrong person's name.
 *
 * ═══ 2. A PUSH PAYLOAD IS RENDERED ON A LOCK SCREEN ═══
 *
 * The payload is encrypted end-to-end, so the push service cannot read it. That
 * is a real guarantee and it is NOT the one people assume.
 *
 * The decrypted notification is shown on a LOCK SCREEN — visible to anyone
 * holding the phone, including the person the message is about. So a push says
 * "Ivan sent you a message"; the message itself stays behind the lock.
 */

const SW_PATH = 'public/sw.js';
const SOURCE_FILES = globSync('src/**/*.{ts,tsx}').map((f) => f.toString());

/** Strip comments — this file's own prose names the things it forbids. */
function code(source: string): string {
  const out: string[] = [];
  let inBlock = false;

  for (const raw of source.split('\n')) {
    let line = raw;

    if (inBlock) {
      const end = line.indexOf('*/');
      if (end === -1) continue;
      inBlock = false;
      line = line.slice(end + 2);
    }

    const block = line.indexOf('/*');
    if (block !== -1) {
      const end = line.indexOf('*/', block + 2);
      if (end === -1) {
        inBlock = true;
        line = line.slice(0, block);
      } else {
        line = line.slice(0, block) + line.slice(end + 2);
      }
    }

    const lineComment = line.indexOf('//');
    if (lineComment !== -1) line = line.slice(0, lineComment);

    if (line.trim()) out.push(line);
  }

  return out.join('\n');
}

describe('the service worker EXISTS', () => {
  it('is committed, not produced by a build step that can silently no-op', () => {
    // This test exists because of a real near-miss.
    //
    // The worker was originally generated by `@serwist/next`, which does NOT
    // support Turbopack — and Next 16 builds with Turbopack by default. It
    // printed a warning, emitted NOTHING, and the build still reported SUCCESS.
    // The app would have shipped a PWA with no service worker at all, and CI
    // would have been perfectly green about it.
    //
    // A feature that is ABSENT rather than broken is the hardest kind to notice.
    // So the worker is hand-written and committed, and this asserts it is there.
    expect(existsSync(SW_PATH)).toBe(true);

    const sw = readFileSync(SW_PATH, 'utf8');
    expect(sw.length).toBeGreaterThan(500);
  });

  it('registers a fetch handler and a push handler', () => {
    const sw = code(readFileSync(SW_PATH, 'utf8'));

    expect(sw).toMatch(/addEventListener\(\s*['"]fetch['"]/);
    expect(sw).toMatch(/addEventListener\(\s*['"]push['"]/);
    expect(sw).toMatch(/addEventListener\(\s*['"]notificationclick['"]/);
  });
});

describe('the service worker never caches an authenticated response', () => {
  const sw = () => code(readFileSync(SW_PATH, 'utf8'));

  it('treats everything under /api/ as authenticated', () => {
    expect(sw()).toMatch(/pathname\.startsWith\(\s*['"]\/api\/['"]\s*\)/);
  });

  it('treats a NAVIGATION as authenticated — our pages are personalised', () => {
    // The subtle one. A cached page is not a cached API response, and it is just
    // as dangerous: the next person on the device is served the last user's
    // dashboard, rendered, from disk.
    expect(sw()).toMatch(/request\.mode === ['"]navigate['"]/);
  });

  it('an offline navigation falls back to a STATIC page, not to a cached one', () => {
    // Falling back to "the last page this device saw" would serve whoever is
    // holding the phone the previous user's screen.
    expect(sw()).toMatch(/OFFLINE_URL/);
  });

  it('only caches assets that are IDENTICAL for every user', () => {
    const source = sw();

    // The allowlist is by PATH, and it is narrow: build output, icons, fonts.
    expect(source).toMatch(/_next\/static/);
    expect(source).toMatch(/isShellAsset/);

    // And the cache write is guarded on a real 200 — caching a 404 means serving
    // it from disk forever.
    expect(source).toMatch(/response\.ok/);
  });

  it('the cache write happens ONLY inside the shell-asset branch', () => {
    const source = sw();

    // If `cache.put` ever appears before the authenticated check, an
    // authenticated response can reach disk. Assert on ORDER, because that is
    // the kind of bug a review misses.
    const authCheck = source.indexOf('isAuthenticated');
    const cachePut = source.indexOf('cache.put');

    expect(authCheck).toBeGreaterThan(-1);
    expect(cachePut).toBeGreaterThan(-1);
    expect(authCheck).toBeLessThan(cachePut);
  });

  it('never caches a non-GET request', () => {
    // Replaying a cached POST would be a duplicate booking.
    expect(sw()).toMatch(/request\.method !== ['"]GET['"]/);
  });
});

describe('a push payload carries no private content', () => {
  const PUSH_CALLERS = SOURCE_FILES.filter((f) => {
    const src = code(readFileSync(f, 'utf8'));
    return /sendPush\s*\(|notify\s*\(\s*db/.test(src);
  });

  it('found the code that sends pushes', () => {
    expect(PUSH_CALLERS.length).toBeGreaterThan(0);
  });

  it('the payload type has no field for a secret or a raw message body', () => {
    const push = readFileSync('src/lib/push/send.ts', 'utf8');

    const payloadType = push.slice(
      push.indexOf('export interface PushPayload'),
      push.indexOf('}', push.indexOf('export interface PushPayload')),
    );

    // A payload is a title, a body, a URL and a tag. Anything named like a
    // secret or a full message has no business being rendered on a lock screen.
    expect(payloadType).not.toMatch(/token|secret|password|cardNumber|messageBody|amountCents/i);
  });

  it('the notification body is LENGTH-CAPPED, so it cannot carry a message', () => {
    // A 4000-character chat message pasted into a notification body is the whole
    // conversation on the lock screen.
    const notifications = readFileSync('src/app-layer/usecases/notifications.ts', 'utf8');

    expect(notifications).toMatch(/NOTIFICATION_BODY_MAX\s*=\s*\d+/);

    const cap = Number(/NOTIFICATION_BODY_MAX\s*=\s*(\d+)/.exec(notifications)?.[1]);
    expect(cap).toBeLessThanOrEqual(300);

    // …and the cap is actually APPLIED, not merely declared.
    expect(notifications).toMatch(/\.slice\(0,\s*NOTIFICATION_BODY_MAX\)/);
  });

  it('notification text is SANITISED — it is rendered, and it comes from users', () => {
    const notifications = code(readFileSync('src/app-layer/usecases/notifications.ts', 'utf8'));

    // A venue name, a player's display name. Both are user-supplied and both end
    // up in a notification title.
    expect(notifications).toMatch(/sanitizePlainText\(input\.title\)/);
    expect(notifications).toMatch(/sanitizePlainText\(input\.body\)/);
  });
});

describe('a dead push subscription is DELETED, not retried forever', () => {
  it('404 and 410 are treated as permanent', () => {
    const push = code(readFileSync('src/lib/push/send.ts', 'utf8'));

    // The push service says the endpoint is gone. It always will be — the browser
    // was cleared, the PWA uninstalled, permission revoked. Retrying it forever
    // backs the queue up behind endpoints that will never accept anything again.
    expect(push).toMatch(/status === 404 \|\| status === 410/);
    expect(push).toMatch(/gone:\s*true/);
  });

  it('a TRANSIENT failure does NOT delete the subscription', () => {
    // Deleting on a 500 would silently unsubscribe a user whose push service had
    // a bad afternoon, and they would never find out why the notifications
    // stopped.
    const notifications = code(readFileSync('src/app-layer/usecases/notifications.ts', 'utf8'));

    expect(notifications).toMatch(/if \(result\.gone\)/);
    expect(notifications).toMatch(/failureCount:\s*\{\s*increment:\s*1\s*\}/);
  });
});

// ── Negative controls ────────────────────────────────────────────────

describe('the rules fire on the code they forbid', () => {
  it('the comment stripper does not let a real violation hide behind a comment', () => {
    // Otherwise a rule could be satisfied by a line of PROSE describing it,
    // while the code beneath does the opposite.
    expect(code('// cache.put(request, response) — forbidden for /api/')).not.toContain(
      'cache.put',
    );
    expect(code('cache.put(request, response.clone());')).toContain('cache.put');
  });

  it('an ordering violation IS detectable', () => {
    // The order assertion above is only meaningful if a reversed order would
    // actually fail. Prove the comparison works.
    const bad = 'cache.put(x);\nif (isAuthenticated(u, r)) return;';
    expect(bad.indexOf('isAuthenticated')).toBeGreaterThan(bad.indexOf('cache.put'));
  });
});
