/**
 * @jest-environment node
 */
import { verifyPassword } from '@/lib/auth/passwords';

/**
 * bcryptjs 3 MUST STILL READ THE HASHES bcryptjs 2 WROTE.
 *
 * ─── Why this test exists ────────────────────────────────────────────
 *
 * bcryptjs 3 emits `$2b$` hashes. bcryptjs 2 emitted `$2a$`.
 *
 * If the new major could not VERIFY the old prefix, then upgrading it would lock
 * every existing user out of their account at their next login — silently, and
 * all at once. There is no error to see: `compare` simply returns false, and the
 * user is told their password is wrong.
 *
 * It can verify them. But "it can" is a fact about today's version, and the whole
 * point of a ratchet is that facts about today's version stop being assumptions
 * about tomorrow's.
 *
 * ─── The hash below is REAL ──────────────────────────────────────────
 *
 * It was generated by bcryptjs 2.4.3 — the version we were on — hashing
 * 'TestPass123!' at 12 rounds. It is not a vector copied from a blog post. (I
 * tried one of those first; it was wrong, and it would have "proven" the opposite
 * conclusion.)
 *
 * If this test ever goes red after a dependency bump, DO NOT MERGE THE BUMP. Every
 * password in the database is a $2a$ hash.
 */

// A genuine bcryptjs 2.4.3 hash of 'TestPass123!' at 12 rounds.
// pragma: allowlist secret
const HASH_FROM_BCRYPTJS_2 = '$2a$12$93YaSzMc9Vq324Ti.YmRUO4bYU86B9c0/OY90Db2L99j3m.5jVz8a';

const PLAINTEXT = 'TestPass123!';

describe('bcrypt cross-major compatibility', () => {
  it('the stored hash really is the OLD $2a$ format', () => {
    // If this ever becomes $2b$, the fixture has been regenerated with the new
    // library and the test has quietly stopped testing anything.
    expect(HASH_FROM_BCRYPTJS_2.startsWith('$2a$')).toBe(true);
  });

  it('verifies a password against a hash written by bcryptjs 2', async () => {
    // THE assertion. If this fails, upgrading bcryptjs locks out every existing
    // user, and they are told their password is wrong.
    await expect(verifyPassword(PLAINTEXT, HASH_FROM_BCRYPTJS_2)).resolves.toBe(true);
  });

  it('still rejects the WRONG password against an old hash', async () => {
    // A compatibility shim that returns true for everything would also "pass"
    // the test above. This is the control.
    await expect(verifyPassword('WrongPassword1!', HASH_FROM_BCRYPTJS_2)).resolves.toBe(false);
  });
});
